<a href="https://colab.research.google.com/github/dubeypriyanshi413-sudo/pandas-data-analysis/blob/main/matrix_operations_tool.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def input_matrix(rows, cols):
    print(f"Enter elements for {rows}x{cols} matrix:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

In [4]:
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

A = input_matrix(rows, cols)
B = input_matrix(rows, cols)

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Enter number of rows: 2
Enter number of columns: 2
Enter elements for 2x2 matrix:
Row 1: 1 2
Row 2: 3 4
Enter elements for 2x2 matrix:
Row 1: 5 6
Row 2: 7 8
Matrix A:
 [[1. 2.]
 [3. 4.]]
Matrix B:
 [[5. 6.]
 [7. 8.]]


In [5]:
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", np.dot(A, B))

Addition:
 [[ 6.  8.]
 [10. 12.]]
Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Multiplication:
 [[19. 22.]
 [43. 50.]]


In [6]:
print("Transpose of A:\n", A.T)

Transpose of A:
 [[1. 3.]
 [2. 4.]]


In [7]:
if rows == cols:
    print("Determinant of A:", np.linalg.det(A))
else:
    print("Determinant not possible (not a square matrix)")

Determinant of A: -2.0000000000000004
